"""empty message

Revision ID: 1bbec939963c
Revises: 0e2dfbc98a52
Create Date: 2020-04-04 18:19:51.421944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbec939963c'
down_revision = '0e2dfbc98a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('facebookLink', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('imageLink', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'image_link')
    op.drop_column('venue', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'imageLink')
    op.drop_column('venue', 'facebookLink')
    # ### end Alembic commands ###
